# Generated by Django 3.2 on 2022-08-24 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImgPredict',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('img_to_p', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
